baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Spotlights'
theme = 'spotlight'
relativeURLs = true

[taxonomies]
	copyrights = 'copyrights'
	tag = 'tags'

[[menus.main]]
	name = 'Spotlights'
	pageRef = '/'
	weight = 10

[[menus.main]]
	name = 'Tags'
	pageRef = '/tags'
	weight = 20

[[menus.main]]
	name = 'Copyright'
	pageRef = '/copyrights'
	weight = 30
